export type ManualEntry = {
  title: string;
  brand: string;
  category: string;
  href: string;
  sourceUrl: string;
  isLocal: boolean;
};

export const manuals: ManualEntry[] = [
  {
    title: `S3M100KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m100kx-24e3fc17.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M100KX/s3m100kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M120KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m120kx-196b81dc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M120KX/s3m120kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M160KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m160kx-e0e55d06.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M160KX/s3m160kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M200KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m200kx-8c68c478.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M200KX/s3m200kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M30KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m30kx-175bf00a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M30KX/s3m30kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M30KX-NIB`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m30kx-nib-6144bf1f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M30KX-NIB/s3m30kxnib.pdf`,
    isLocal: true,
  },
  {
    title: `S3M40KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m40kx-e6f27b36.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M40KX/s3m40kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M40KX-NIB`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m40kx-nib-d7c7083e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M40KX-NIB/s3m40kxnib.pdf`,
    isLocal: true,
  },
  {
    title: `S3M60KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m60kx-b75688c1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M60KX/s3m60kx.pdf`,
    isLocal: true,
  },
  {
    title: `S3M80KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/s3m80kx-c46912bc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/S3M80KX/s3m80kx.pdf`,
    isLocal: true,
  },
  {
    title: `SU100KX2`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su100kx2-e9a5c9aa.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU100KX2/su100kx2.pdf`,
    isLocal: true,
  },
  {
    title: `SU120KX2`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su120kx2-5d212376.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU120KX2/su120kx2.pdf`,
    isLocal: true,
  },
  {
    title: `SU20KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su20kx-f40f5307.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU20KX/su20kx.pdf`,
    isLocal: true,
  },
  {
    title: `SU40KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su40kx-81002e62.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU40KX/su40kx.pdf`,
    isLocal: true,
  },
  {
    title: `SU60KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su60kx-b23fa9fe.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU60KX/su60kx.pdf`,
    isLocal: true,
  },
  {
    title: `SU80KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su80kx-aed66873.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU80KX/su80kx.pdf`,
    isLocal: true,
  },
  {
    title: `SU80KX2`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/su80kx2-fd71d520.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SU80KX2/su80kx2.pdf`,
    isLocal: true,
  },
  {
    title: `SUTX20K`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/sutx20k-c948ccdb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SUTX20K/sutx20k.pdf`,
    isLocal: true,
  },
  {
    title: `SUTX40K`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/sutx40k-e44cea8a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SUTX40K/sutx40k.pdf`,
    isLocal: true,
  },
  {
    title: `SVT10KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svt10kx-6cf49ff3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVT10KX/svt10kx.pdf`,
    isLocal: true,
  },
  {
    title: `SVT20KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svt20kx-24eff587.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVT20KX/svt20kx.pdf`,
    isLocal: true,
  },
  {
    title: `SVT30KX`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svt30kx-a99fd898.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVT30KX/svt30kx.pdf`,
    isLocal: true,
  },
  {
    title: `SVX120KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx120kl-e0bba2a4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX120KL/svx120kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX150KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx150kl-d432e4a3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX150KL/svx150kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX180KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx180kl-9a2818db.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX180KL/svx180kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX210KL7P`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx210kl7p-0d051bc0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX210KL7P/svx210kl7p.pdf`,
    isLocal: true,
  },
  {
    title: `SVX210KL8P`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx210kl8p-ee8f206b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX210KL8P/svx210kl8p.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30kl-9383c98f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KL/svx30kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KM1P2B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30km1p2b-0723ec7c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KM1P2B/SVX30KM1P2B.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KM1P3B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30km1p3b-018fb4d5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KM1P3B/svx30km1p3b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KM1P4B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30km1p4b-0b7b65d8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KM1P4B/svx30km1p4b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KM1P5B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30km1p5b-ddd599b4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KM1P5B/svx30km1p5b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KS1P2B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30ks1p2b-e3f383dc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KS1P2B/svx30ks1p2b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX30KS1P3B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx30ks1p3b-b4761295.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX30KS1P3B/svx30ks1p3b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX60KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx60kl-e3764b2d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX60KL/svx60kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX60KM2P3B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx60km2p3b-7d42e5f4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX60KM2P3B/svx60km2p3b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX60KM2P4B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx60km2p4b-4b2d7892.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX60KM2P4B/svx60km2p4b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX60KM2P5B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx60km2p5b-8c6e07d1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX60KM2P5B/svx60km2p5b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX60KS2P3B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx60ks2p3b-81c5a72f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX60KS2P3B/svx60ks2p3b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX90KL`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx90kl-0515269e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX90KL/svx90kl.pdf`,
    isLocal: true,
  },
  {
    title: `SVX90KM3P5B`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx90km3p5b-87c41ee2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX90KM3P5B/svx90km3p5b.pdf`,
    isLocal: true,
  },
  {
    title: `SVX90KS3P`,
    brand: `3 Phase 400v`,
    category: `General`,
    href: `/manuals-pdfs/3-phase-400v/general/svx90ks3p-77b32ce3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/3 Phase 400v/SVX90KS3P/svx90ks3p.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS 350-500-650`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-350-500-650-1c8d845b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS 350-500-650.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS BE550 BE700G`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-be550-be700g-9cb66efd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS BE550 BE700G.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS ES 400-550-700`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-es-400-550-700-457e7af0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS ES 400-550-700.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS Pro 1200GI & 1500GI`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-pro-1200gi-1500gi-abfbcdcb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS Pro 1200GI & 1500GI.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS Pro 900`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-pro-900-77ee208a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS Pro 900.pdf`,
    isLocal: true,
  },
  {
    title: `APC Back-UPS RS 550GI`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-back-ups-rs-550gi-3d190074.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC Back-UPS RS 550GI.pdf`,
    isLocal: true,
  },
  {
    title: `APC BE325-UK`,
    brand: `APC`,
    category: `APC Back-UPS`,
    href: `/manuals-pdfs/apc/apc-back-ups/apc-be325-uk-932570a1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Back-UPS/APC BE325-UK.pdf`,
    isLocal: true,
  },
  {
    title: `APC SRT72RMBP`,
    brand: `APC`,
    category: `APC Extended Batteries`,
    href: `/manuals-pdfs/apc/apc-extended-batteries/apc-srt72rmbp-34e3ec81.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Extended Batteries/APC SRT72RMBP.pdf`,
    isLocal: true,
  },
  {
    title: `SRT192BP`,
    brand: `APC`,
    category: `APC Extended Batteries`,
    href: `/manuals-pdfs/apc/apc-extended-batteries/srt192bp-482591b7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Extended Batteries/SRT192BP.pdf`,
    isLocal: true,
  },
  {
    title: `SRT96BP SRT72BP`,
    brand: `APC`,
    category: `APC Extended Batteries`,
    href: `/manuals-pdfs/apc/apc-extended-batteries/srt96bp-srt72bp-cc5f38ad.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Extended Batteries/SRT96BP SRT72BP.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 1`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-1-15936a78.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC1.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 10`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-10-ecde8900.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC10.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 11`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-11-0e1d9bdd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC11.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 110`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-110-71ae9fdb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC110.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 113`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-113-9202a63a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC113.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 12`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-12-e3b9a7be.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC12.pdf`,
    isLocal: true,
  },
  {
    title: `APC RBC 7`,
    brand: `APC`,
    category: `APC Replacement Batteries`,
    href: `/manuals-pdfs/apc/apc-replacement-batteries/apc-rbc-7-1fdb036a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Replacement Batteries/APC RBC7.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS 420 620`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-420-620-bbc90bec.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS 420 620.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS 5000 SUA5000RMi5U`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-5000-sua5000rmi5u-e5b17913.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS 5000 SUA5000RMi5U.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS 750 1000 SUA750RMi2u SUA1000RMi2u`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-750-1000-sua750rmi2u-sua1000rmi2u-ffbb50c0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS 750 1000 SUA750RMi2u SUA1000RMi2u.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS 750RMi2U 750 1000 1500 3000 Manual`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-750rmi2u-750-1000-1500-3000-manual-e6884708.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS 750RMi2U 750 1000 1500 3000 Manual.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RM SMT750RMi2U SMT1000RMi2U SMT1500RMi2U SMT2200RMi2U SMT3000RMi2U`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-rm-smt750rmi2u-smt1000rmi2u-smt1500rmi2u-smt2200rmi2u-smt3-f737e07d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS RM SMT750RMi2U SMT1000RMi2U SMT1500RMi2U SMT2200RMi2U SMT3000RMi2U.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS SMT750i SMT1000I SMT1500I SMT2200i SMT3000I`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-smt750i-smt1000i-smt1500i-smt2200i-smt3000i-f1d273f9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS SMT750i SMT1000I SMT1500I SMT2200i SMT3000I.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS SMT750RMi2U SMT1000RMI2U SMT1500RMI2`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-smt750rmi2u-smt1000rmi2u-smt1500rmi2-aba661a7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS SMT750RMi2U SMT1000RMI2U SMT1500RMI2.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS SRC250 SRC450`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-src250-src450-f8990f2a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS SRC250 SRC450.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS SUA1000RMi1U SUA750RMi1U`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smart-ups-sua1000rmi1u-sua750rmi1u-c7499036.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC Smart-UPS SUA1000RMi1U SUA750RMi1U.pdf`,
    isLocal: true,
  },
  {
    title: `APC SMT750I SMT1000I SMT1500I SMT2200I SMT3000I`,
    brand: `APC`,
    category: `APC Smart UPS`,
    href: `/manuals-pdfs/apc/apc-smart-ups/apc-smt750i-smt1000i-smt1500i-smt2200i-smt3000i-24372856.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS/APC SMT750I SMT1000I SMT1500I SMT2200I SMT3000I.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT 15kVA 20kVA SRT15KRMXLI SRT20KRMXLi`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-15kva-20kva-srt15krmxli-srt20krmxli-78eacf43.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT 15kVA 20kVA SRT15KRMXLI SRT20KRMXLi.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT 5kVA 6kVA SRT5kRMXLi SRT5kXLi SRT6kRMXLi SRT6kRMXLi`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-5kva-6kva-srt5krmxli-srt5kxli-srt6krmxli-srt6krmxli-91b613ac.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT 5kVA 6kVA SRT5kRMXLi SRT5kXLi SRT6kRMXLi SRT6kRMXLi.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT 8kVA 10kVA SRT8KXLI SRT8KRMXLI SRT10kXLI SRT10KRMXLI`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-8kva-10kva-srt8kxli-srt8krmxli-srt10kxli-srt10krmxli-500c1262.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT 8kVA 10kVA SRT8KXLI SRT8KRMXLI SRT10kXLI SRT10KRMXLI.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT SRT2200XLi SRT2200RMXLi SRT3000XLi SRT3000RMXLI`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-srt2200xli-srt2200rmxli-srt3000xli-srt3000rmxli-ac637624.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT SRT2200XLi SRT2200RMXLi SRT3000XLi SRT3000RMXLI.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT SURT1000RMXLi SURT2000RMXLI`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-surt1000rmxli-surt2000rmxli-2035c20c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT SURT1000RMXLi SURT2000RMXLI.pdf`,
    isLocal: true,
  },
  {
    title: `APC Smart-UPS RT SURT1000XLi SURT2000XLi`,
    brand: `APC`,
    category: `APC Smart-UPS RT`,
    href: `/manuals-pdfs/apc/apc-smart-ups-rt/apc-smart-ups-rt-surt1000xli-surt2000xli-a3ccba14.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Smart-UPS RT/APC Smart-UPS RT SURT1000XLi SURT2000XLi.pdf`,
    isLocal: true,
  },
  {
    title: `APC SYA4K8I SYA4k16I`,
    brand: `APC`,
    category: `APC Symmetra`,
    href: `/manuals-pdfs/apc/apc-symmetra/apc-sya4k8i-sya4k16i-a7f118bb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Symmetra/APC SYA4K8I SYA4k16I.pdf`,
    isLocal: true,
  },
  {
    title: `APC Symmetra RM 2-6kVA 8-12kVA`,
    brand: `APC`,
    category: `APC Symmetra`,
    href: `/manuals-pdfs/apc/apc-symmetra/apc-symmetra-rm-2-6kva-8-12kva-267c05ca.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/APC/APC Symmetra/APC Symmetra RM 2-6kVA 8-12kVA.pdf`,
    isLocal: true,
  },
  {
    title: `IDG 1200`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/idg-1200-71ae9f9f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IDG/IDG 1200.pdf`,
    isLocal: true,
  },
  {
    title: `IDG 1600`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/idg-1600-7f07c704.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IDG/IDG 1600.pdf`,
    isLocal: true,
  },
  {
    title: `IDG 400`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/idg-400-c1bd9730.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IDG/IDG 400.pdf`,
    isLocal: true,
  },
  {
    title: `IDG 600`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/idg-600-c01d24b3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IDG/IDG 600.pdf`,
    isLocal: true,
  },
  {
    title: `IDG 800`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/idg-800-8890ed1a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IDG/IDG 800.pdf`,
    isLocal: true,
  },
  {
    title: `IPG 600 UK`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/ipg-600-uk-4073b54e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IPG/IPG 600 UK.pdf`,
    isLocal: true,
  },
  {
    title: `IPG 800 UK`,
    brand: `Reillo`,
    category: `IDG`,
    href: `/manuals-pdfs/reillo/idg/ipg-800-uk-7f9b411e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/IPG/IPG 800 UK.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 10-A0`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-10-a0-5a8f49a2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 10-S1`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-10-s1-9f65a971.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 10-S1.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 10-S2`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-10-s2-c5c56280.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 10-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 12-A0`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-12-a0-b79073da.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 12-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 12-S1`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-12-s1-f1fe4275.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 12-S1.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 12-S2`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-12-s2-fabccdb8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 12-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 15-A0`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-15-a0-0fbd73b8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 15-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 15-S2`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-15-s2-fa75775a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 15-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 20-A0`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-20-a0-943a94c8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCM 20-S2`,
    brand: `Reillo`,
    category: `MCM`,
    href: `/manuals-pdfs/reillo/mcm/mcm-20-s2-aca8f3f0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCM/MCM 20-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 10-A0`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-10-a0-c4a5f70e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 10-S1`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-10-s1-67355e4c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 10-S1.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 10-S2`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-10-s2-a6fb4912.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 10-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 12-A0`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-12-a0-9cf9e178.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 12-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 12-S1`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-12-s1-736d47e6.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 12-S1.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 12-S2`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-12-s2-124cdf25.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 12-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 15-A0`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-15-a0-405cede0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 15-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 15-S2`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-15-s2-7bf91740.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 15-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 20-A0`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-20-a0-4446ac93.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MCT 20-S2`,
    brand: `Reillo`,
    category: `MCT`,
    href: `/manuals-pdfs/reillo/mct/mct-20-s2-3ee6ca43.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MCT/MCT 20-S2.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 100`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-100-a16fa4cc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 100.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 120`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-120-0de6e1e7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 120.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 160`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-160-cb29660c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 160.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 200`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-200-00ec5843.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 200.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 250`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-250-052899bf.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 250.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 300`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-300-703d3858.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 300.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 400`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-400-21bde65b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 400.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 500`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-500-b39d1d62.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 500.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 600`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-600-728407a1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 600.pdf`,
    isLocal: true,
  },
  {
    title: `MHE 800`,
    brand: `Reillo`,
    category: `MHE`,
    href: `/manuals-pdfs/reillo/mhe/mhe-800-49f660d7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHE/MHE 800.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 100`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-100-e4855b27.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 100.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 120`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-120-3ffee780.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 120.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 160`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-160-412da605.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 160.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 200`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-200-27114204.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 200.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 250`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-250-539f0101.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 250.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 300`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-300-345ab2ed.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 300.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 400`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-400-fcdb90a3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 400.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 500`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-500-1472bba3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 500.pdf`,
    isLocal: true,
  },
  {
    title: `MHT 600`,
    brand: `Reillo`,
    category: `MHT`,
    href: `/manuals-pdfs/reillo/mht/mht-600-4f503d98.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MHT/MHT 600.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 10-A0`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-10-a0-683e2cbd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 100`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-100-b4c04740.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 100.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 15`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-15-87abdab4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 15.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 20-A0`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-20-a0-dc508354.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 30`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-30-8fd36d6b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 30.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 40`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-40-b23a8459.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 40.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 60`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-60-e1d58b61.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 60.pdf`,
    isLocal: true,
  },
  {
    title: `MPM 80`,
    brand: `Reillo`,
    category: `MPM`,
    href: `/manuals-pdfs/reillo/mpm/mpm-80-1adcdbd4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPM/MPM 80.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 10`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-10-65cf0fcc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 10.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 100`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-100-75097a4e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 100.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 120`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-120-75b41024.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 120.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 15`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-15-a27ea516.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 15.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 160`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-160-acc7fed7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 160.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 20`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-20-efc31756.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 20.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 200`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-200-944afd47.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 200.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 30`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-30-da68a95b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 30.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 40`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-40-a0d4b7e0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 40.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 60`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-60-af245138.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 60.pdf`,
    isLocal: true,
  },
  {
    title: `MPT 80`,
    brand: `Reillo`,
    category: `MPT`,
    href: `/manuals-pdfs/reillo/mpt/mpt-80-9fabd5fa.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPT/MPT 80.pdf`,
    isLocal: true,
  },
  {
    title: `MPW 25`,
    brand: `Reillo`,
    category: `MPW`,
    href: `/manuals-pdfs/reillo/mpw/mpw-25-4ed67c95.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPW/MPW 25.pdf`,
    isLocal: true,
  },
  {
    title: `MPW 42`,
    brand: `Reillo`,
    category: `MPW`,
    href: `/manuals-pdfs/reillo/mpw/mpw-42-79ca90a0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPW/MPW 42.pdf`,
    isLocal: true,
  },
  {
    title: `MPW CBC 130`,
    brand: `Reillo`,
    category: `MPW`,
    href: `/manuals-pdfs/reillo/mpw/mpw-cbc-130-8fd95dfb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPW/MPW CBC 130.pdf`,
    isLocal: true,
  },
  {
    title: `MPW PWC 130`,
    brand: `Reillo`,
    category: `MPW`,
    href: `/manuals-pdfs/reillo/mpw/mpw-pwc-130-ba85cfa7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPW/MPW PWC 130.pdf`,
    isLocal: true,
  },
  {
    title: `MPW PWC 300`,
    brand: `Reillo`,
    category: `MPW`,
    href: `/manuals-pdfs/reillo/mpw/mpw-pwc-300-22db067b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MPW/MPW PWC 300.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 10-A0`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-10-a0-d976ab6e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 10-A0ER`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-10-a0er-4bcdcdf9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 10-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 10-A0T`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-10-a0t-a7d14abf.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 10-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 10-T1`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-10-t1-480613ee.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 10-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 10-T4`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-10-t4-ed95c23f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 10-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 12-A0`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-12-a0-671e5061.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 12-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 12-A0ER`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-12-a0er-734bf9c2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 12-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 12-A0T`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-12-a0t-1b81f806.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 12-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 12-T1`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-12-t1-512f164b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 12-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 12-T4`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-12-t4-2ac5457f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 12-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 15-A0`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-15-a0-6adb18e5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 15-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 15-A0ER`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-15-a0er-794783f3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 15-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 15-A0T`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-15-a0t-b3aec6c1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 15-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 15-T1`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-15-t1-7e0960cd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 15-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 15-T4`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-15-t4-a09293c5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 15-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 20-A0`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-20-a0-103b0b5d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 20-A0ER`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-20-a0er-75445195.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 20-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 20-A0T`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-20-a0t-33d1b129.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 20-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 20-T1`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-20-t1-3505474b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 20-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MSM 20-T4`,
    brand: `Reillo`,
    category: `MSM`,
    href: `/manuals-pdfs/reillo/msm/msm-20-t4-213dfe1c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MSM/MSM 20-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 10-A0`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-10-a0-6104e584.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MST 10-A0ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-10-a0er-e1d2cd97.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 10-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 10-A0T`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-10-a0t-a8ce7202.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 10-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MST 10-T1`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-10-t1-f25f6ecd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 10-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MST 10-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-10-t4-3dbc3dd7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 10-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 100 SB`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-100-sb-9867ab8a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 100 SB.pdf`,
    isLocal: true,
  },
  {
    title: `MST 100`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-100-6eaf8e14.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 100.pdf`,
    isLocal: true,
  },
  {
    title: `MST 100ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-100er-ca4fc6c6.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 100ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 12-A0`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-12-a0-b6742f4a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 12-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MST 12-A0ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-12-a0er-b004287d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 12-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 12-A0T`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-12-a0t-a0aa6640.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 12-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MST 12-T1`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-12-t1-0f25668d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 12-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MST 12-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-12-t4-5ee83a4f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 12-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 125`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-125-51564b95.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 125.pdf`,
    isLocal: true,
  },
  {
    title: `MST 15-A0`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-15-a0-2aef09f5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 15-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MST 15-A0T`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-15-a0t-694eceaf.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 15-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MST 15-T1`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-15-t1-2246a2c2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 15-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MST 15-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-15-t4-99c32402.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 15-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 160`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-160-28f32162.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 160.pdf`,
    isLocal: true,
  },
  {
    title: `MST 160ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-160er-2a165319.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 160ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 20-A0`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-20-a0-6693fe56.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MST 20-A0ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-20-a0er-67c56011.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 20-A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 20-A0T`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-20-a0t-517ab3d3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 20-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MST 20-T1`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-20-t1-a4fd323f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 20-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MST 20-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-20-t4-30422609.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 20-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 200`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-200-96525e5d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 200.pdf`,
    isLocal: true,
  },
  {
    title: `MST 200ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-200er-5e9c36be.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 200ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 30-ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-30-er-3e1b85cd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 30-ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 30-T1`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-30-t1-dea90ee4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 30-T1.pdf`,
    isLocal: true,
  },
  {
    title: `MST 30-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-30-t4-806e4f40.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 30-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 40-A0`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-40-a0-6bfb4056.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 40-A0.pdf`,
    isLocal: true,
  },
  {
    title: `MST 40-A0T`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-40-a0t-fa9c83c0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 40-A0T.pdf`,
    isLocal: true,
  },
  {
    title: `MST 40-T4`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-40-t4-3b7bf149.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 40-T4.pdf`,
    isLocal: true,
  },
  {
    title: `MST 40A0ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-40a0er-9ab77196.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 40A0ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 60 SB`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-60-sb-20717bfb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 60 SB.pdf`,
    isLocal: true,
  },
  {
    title: `MST 60`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-60-86403d8a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 60.pdf`,
    isLocal: true,
  },
  {
    title: `MST 60ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-60er-b66e2329.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 60ER.pdf`,
    isLocal: true,
  },
  {
    title: `MST 80 SB`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-80-sb-83eec477.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 80 SB.pdf`,
    isLocal: true,
  },
  {
    title: `MST 80`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-80-97f978b4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 80.pdf`,
    isLocal: true,
  },
  {
    title: `MST 80ER`,
    brand: `Reillo`,
    category: `MST`,
    href: `/manuals-pdfs/reillo/mst/mst-80er-e3d8e0a0.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/MST/MST 80ER.pdf`,
    isLocal: true,
  },
  {
    title: `NPW 1000`,
    brand: `Reillo`,
    category: `NPW`,
    href: `/manuals-pdfs/reillo/npw/npw-1000-c4d933dc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NPW/NPW 1000.pdf`,
    isLocal: true,
  },
  {
    title: `NPW 1500`,
    brand: `Reillo`,
    category: `NPW`,
    href: `/manuals-pdfs/reillo/npw/npw-1500-9acc021b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NPW/NPW 1500.pdf`,
    isLocal: true,
  },
  {
    title: `NPW 2000`,
    brand: `Reillo`,
    category: `NPW`,
    href: `/manuals-pdfs/reillo/npw/npw-2000-c2cb7259.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NPW/NPW 2000.pdf`,
    isLocal: true,
  },
  {
    title: `NPW 800`,
    brand: `Reillo`,
    category: `NPW`,
    href: `/manuals-pdfs/reillo/npw/npw-800-9f84e54b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NPW/NPW 800.pdf`,
    isLocal: true,
  },
  {
    title: `NXE 250`,
    brand: `Reillo`,
    category: `NXE`,
    href: `/manuals-pdfs/reillo/nxe/nxe-250-52e0faf3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NXE/NXE 250.pdf`,
    isLocal: true,
  },
  {
    title: `NXE 300`,
    brand: `Reillo`,
    category: `NXE`,
    href: `/manuals-pdfs/reillo/nxe/nxe-300-c53a89a2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/NXE/NXE 300.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 1000`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-1000-b02b981b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 1000.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 1500`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-1500-e856bf40.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 1500.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 2200 ER`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-2200-er-5d202d2d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 2200 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 2200`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-2200-d97ae564.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 2200.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 3000 ER`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-3000-er-58d0c393.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 3000 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SDH 3000`,
    brand: `Reillo`,
    category: `SDH`,
    href: `/manuals-pdfs/reillo/sdh/sdh-3000-f869d02d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDH/SDH 3000.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 10000 TM`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-10000-tm-6b85c40c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 10000 TM.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 10000`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-10000-b1ec566e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 10000.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 3300`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-3300-d2f2f688.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 3300.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 4000`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-4000-9bb70457.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 4000.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 5000`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-5000-8e2cbffb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 5000.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 6000`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-6000-8d9b5e4d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 6000.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 6500 TM`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-6500-tm-bf1044d3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 6500 TM.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 8000 TM`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-8000-tm-db616767.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 8000 TM.pdf`,
    isLocal: true,
  },
  {
    title: `SDL 8000`,
    brand: `Reillo`,
    category: `SDL`,
    href: `/manuals-pdfs/reillo/sdl/sdl-8000-df1b882d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDL/SDL 8000.pdf`,
    isLocal: true,
  },
  {
    title: `SDU DI ER`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-di-er-fbaf66a4.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 10000 DI ER.pdf`,
    isLocal: true,
  },
  {
    title: `SDU DI`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-di-62e1d344.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 10000 DI.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 10000`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-10000-fd3a927c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 10000.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 5000 PD`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-5000-pd-cb181298.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 5000 PD.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 5000`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-5000-b52844a2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 5000.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 6000 ER`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-6000-er-90411a06.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 6000 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 6000 PD`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-6000-pd-29f08ce9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 6000 PD.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 6000`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-6000-8616e23b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 6000.pdf`,
    isLocal: true,
  },
  {
    title: `SDU 8000`,
    brand: `Reillo`,
    category: `SDU`,
    href: `/manuals-pdfs/reillo/sdu/sdu-8000-8d334bb8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SDU/SDU 8000.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 1000 ER`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-1000-er-d3c4f5e5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 1000 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 1000`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-1000-48a50de3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 1000.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 1500`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-1500-5c0ee3fc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 1500.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 2200 ER`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-2200-er-63bdc075.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 2200 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 2200`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-2200-561912fe.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 2200.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 3000 ER`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-3000-er-38e6fe88.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 3000 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 3000`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-3000-c4ff731a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 3000.pdf`,
    isLocal: true,
  },
  {
    title: `SEP 700`,
    brand: `Reillo`,
    category: `SEP`,
    href: `/manuals-pdfs/reillo/sep/sep-700-178738f3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SEP/SEP 700.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 10 ER`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-10-er-f6dee2a1.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 10 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 10-A0`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-10-a0-3dfa015f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 10-A0.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 10`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-10-8ca494b5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 10.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 15`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-15-79533dcc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 15.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 20 ER`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-20-er-56dcdbbc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 20 ER.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 20-A0`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-20-a0-e2804495.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 20-A0.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 20`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-20-85707bd9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 20.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 8-A0`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-8-a0-f19e9a34.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 8-A0.pdf`,
    isLocal: true,
  },
  {
    title: `SPH 8`,
    brand: `Reillo`,
    category: `SPH`,
    href: `/manuals-pdfs/reillo/sph/sph-8-c2ebbd71.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPH/SPH 8.pdf`,
    isLocal: true,
  },
  {
    title: `SPM 6-A0`,
    brand: `Reillo`,
    category: `SPM`,
    href: `/manuals-pdfs/reillo/spm/spm-6-a0-856b1dbb.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPM/SPM 6-A0.pdf`,
    isLocal: true,
  },
  {
    title: `SPM 6`,
    brand: `Reillo`,
    category: `SPM`,
    href: `/manuals-pdfs/reillo/spm/spm-6-1cd69424.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPM/SPM 6.pdf`,
    isLocal: true,
  },
  {
    title: `SPT 10000`,
    brand: `Reillo`,
    category: `SPT`,
    href: `/manuals-pdfs/reillo/spt/spt-10000-4933a948.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPT/SPT 10000.pdf`,
    isLocal: true,
  },
  {
    title: `SPT 6500`,
    brand: `Reillo`,
    category: `SPT`,
    href: `/manuals-pdfs/reillo/spt/spt-6500-d3f6c66c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPT/SPT 6500.pdf`,
    isLocal: true,
  },
  {
    title: `SPT 8000`,
    brand: `Reillo`,
    category: `SPT`,
    href: `/manuals-pdfs/reillo/spt/spt-8000-01ba1f15.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPT/SPT 8000.pdf`,
    isLocal: true,
  },
  {
    title: `SPW 5000`,
    brand: `Reillo`,
    category: `SPW`,
    href: `/manuals-pdfs/reillo/spw/spw-5000-280758b3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPW/SPW 5000.pdf`,
    isLocal: true,
  },
  {
    title: `SPW 6000`,
    brand: `Reillo`,
    category: `SPW`,
    href: `/manuals-pdfs/reillo/spw/spw-6000-4d83db69.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/SPW/SPW 6000.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 1100`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-1100-b3215ebf.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 1100.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 1500`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-1500-b7d4e723.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 1500.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 2200`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-2200-dd4a39f8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 2200.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 2200ER`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-2200er-7b2c035b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 2200ER.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 3000`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-3000-57826fc7.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 3000.pdf`,
    isLocal: true,
  },
  {
    title: `VSD 3000ER`,
    brand: `Reillo`,
    category: `VSD`,
    href: `/manuals-pdfs/reillo/vsd/vsd-3000er-c2a2959b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSD/VSD 3000ER.pdf`,
    isLocal: true,
  },
  {
    title: `VSR 1100`,
    brand: `Reillo`,
    category: `VSR`,
    href: `/manuals-pdfs/reillo/vsr/vsr-1100-efcdf243.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSR/VSR 1100.pdf`,
    isLocal: true,
  },
  {
    title: `VSR 800`,
    brand: `Reillo`,
    category: `VSR`,
    href: `/manuals-pdfs/reillo/vsr/vsr-800-c19d6b63.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VSR/VSR 800.pdf`,
    isLocal: true,
  },
  {
    title: `VST 1100`,
    brand: `Reillo`,
    category: `VST`,
    href: `/manuals-pdfs/reillo/vst/vst-1100-e3be4da2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VST/VST 1100.pdf`,
    isLocal: true,
  },
  {
    title: `VST 1500`,
    brand: `Reillo`,
    category: `VST`,
    href: `/manuals-pdfs/reillo/vst/vst-1500-a09bf704.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VST/VST 1500.pdf`,
    isLocal: true,
  },
  {
    title: `VST 2000`,
    brand: `Reillo`,
    category: `VST`,
    href: `/manuals-pdfs/reillo/vst/vst-2000-790d774a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VST/VST 2000.pdf`,
    isLocal: true,
  },
  {
    title: `VST 800`,
    brand: `Reillo`,
    category: `VST`,
    href: `/manuals-pdfs/reillo/vst/vst-800-149b793f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Reillo/UPS/VST/VST 800.pdf`,
    isLocal: true,
  },
  {
    title: `avrx550u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/avrx550u-fcfd0b49.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/avrx550u.pdf`,
    isLocal: true,
  },
  {
    title: `avrx550ud`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/avrx550ud-2f997319.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/avrx550ud.pdf`,
    isLocal: true,
  },
  {
    title: `avrx750u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/avrx750u-fd51b2b2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/avrx750u.pdf`,
    isLocal: true,
  },
  {
    title: `avrx750ud`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/avrx750ud-9a404f9f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/avrx750ud.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsint1000`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsint1000-57aa00a9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsint1000.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsint1500xl`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsint1500xl-e014eef5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsint1500xl.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsint800`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsint800-177d497b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsint800.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx1000`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx1000-25b8c129.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx1000.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx1000d`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx1000d-21c7cbd5.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx1000d.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx1500`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx1500-96f51c1c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx1500.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx1500d`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx1500d-01b908cd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx1500d.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx450`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx450-3e8a5368.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx450.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx450d`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx450d-3b5883e3.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx450d.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx650`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx650-260b2f30.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx650.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx650d`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx650d-7f7876a2.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx650d.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx850`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx850-2c973b41.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx850.pdf`,
    isLocal: true,
  },
  {
    title: `omnivsx850d`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnivsx850d-93785434.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnivsx850d.pdf`,
    isLocal: true,
  },
  {
    title: `omnix350hg`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/omnix350hg-8a37897f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/omnix350hg.pdf`,
    isLocal: true,
  },
  {
    title: `smartint1500`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smartint1500-f3479e06.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smartint1500.pdf`,
    isLocal: true,
  },
  {
    title: `smartint2200vs`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smartint2200vs-80d6ed54.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smartint2200vs.pdf`,
    isLocal: true,
  },
  {
    title: `smartint3000vs`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smartint3000vs-f60dd49a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smartint3000vs.pdf`,
    isLocal: true,
  },
  {
    title: `smx1000lcd`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1000lcd-9ab896f8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1000lcd.pdf`,
    isLocal: true,
  },
  {
    title: `smx1000rt2u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1000rt2u-a3395892.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1000rt2u.pdf`,
    isLocal: true,
  },
  {
    title: `smx1050slt`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1050slt-a94ef5bc.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1050slt.pdf`,
    isLocal: true,
  },
  {
    title: `smx1200xlhg`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1200xlhg-5f9354ab.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1200xlhg.pdf`,
    isLocal: true,
  },
  {
    title: `smx1200xlhgl`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1200xlhgl-d00b636f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1200xlhgl.pdf`,
    isLocal: true,
  },
  {
    title: `smx1500lcd`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1500lcd-a65ecb34.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1500lcd.pdf`,
    isLocal: true,
  },
  {
    title: `smx1500lcdt`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1500lcdt-26720403.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1500lcdt.pdf`,
    isLocal: true,
  },
  {
    title: `smx1500slt`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1500slt-57e8471a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1500slt.pdf`,
    isLocal: true,
  },
  {
    title: `smx1500xlrt2u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx1500xlrt2u-86050bb6.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx1500xlrt2u.pdf`,
    isLocal: true,
  },
  {
    title: `smx2200xlrt2u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx2200xlrt2u-724c155e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx2200xlrt2u.pdf`,
    isLocal: true,
  },
  {
    title: `smx3000xlrt2u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx3000xlrt2u-8cad64b8.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx3000xlrt2u.pdf`,
    isLocal: true,
  },
  {
    title: `smx3000xlrt2ua`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx3000xlrt2ua-da707461.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx3000xlrt2ua.pdf`,
    isLocal: true,
  },
  {
    title: `smx5000xlrt3u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx5000xlrt3u-9a0431bd.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx5000xlrt3u.pdf`,
    isLocal: true,
  },
  {
    title: `smx500rt1u`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx500rt1u-bb7007d9.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx500rt1u.pdf`,
    isLocal: true,
  },
  {
    title: `smx700hg`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx700hg-3fffec0c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx700hg.pdf`,
    isLocal: true,
  },
  {
    title: `smx700hgl`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx700hgl-5421af16.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx700hgl.pdf`,
    isLocal: true,
  },
  {
    title: `smx750slt`,
    brand: `Tripplite`,
    category: `Tripplite In-line`,
    href: `/manuals-pdfs/tripplite/tripplite-in-line/smx750slt-91c0233c.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite In-line/smx750slt.pdf`,
    isLocal: true,
  },
  {
    title: `su10000rt3ug`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su10000rt3ug-52228f4b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su10000rt3ug.pdf`,
    isLocal: true,
  },
  {
    title: `su10krt3uhv`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su10krt3uhv-d33ad63a.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su10krt3uhv.pdf`,
    isLocal: true,
  },
  {
    title: `su12krt4uhw`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su12krt4uhw-a55d8b1d.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su12krt4uhw.pdf`,
    isLocal: true,
  },
  {
    title: `su16krtg`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su16krtg-cdb6c0f6.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su16krtg.pdf`,
    isLocal: true,
  },
  {
    title: `su16krthw`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su16krthw-4fe35358.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su16krthw.pdf`,
    isLocal: true,
  },
  {
    title: `su20krtg`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su20krtg-057771de.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su20krtg.pdf`,
    isLocal: true,
  },
  {
    title: `su20krthw`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su20krthw-814e4199.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su20krthw.pdf`,
    isLocal: true,
  },
  {
    title: `su6000rt4uhvg`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su6000rt4uhvg-f6e6534e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su6000rt4uhvg.pdf`,
    isLocal: true,
  },
  {
    title: `su6000rt4uhvhw`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su6000rt4uhvhw-8cccf986.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su6000rt4uhvhw.pdf`,
    isLocal: true,
  },
  {
    title: `su8000rt3ug`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su8000rt3ug-353ea4ac.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su8000rt3ug.pdf`,
    isLocal: true,
  },
  {
    title: `su8000rt3uhw`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/su8000rt3uhw-f280f24b.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/su8000rt3uhw.pdf`,
    isLocal: true,
  },
  {
    title: `suint1000lcd2u`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint1000lcd2u-7589a742.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint1000lcd2u.pdf`,
    isLocal: true,
  },
  {
    title: `suint2000xlcd`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint2000xlcd-8a465079.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint2000xlcd.pdf`,
    isLocal: true,
  },
  {
    title: `suint2200lcd2u`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint2200lcd2u-0012b07f.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint2200lcd2u.pdf`,
    isLocal: true,
  },
  {
    title: `suint3000lcd2u`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint3000lcd2u-cafa23e6.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint3000lcd2u.pdf`,
    isLocal: true,
  },
  {
    title: `suint3000rtxl2u`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint3000rtxl2u-87e38a7e.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint3000rtxl2u.pdf`,
    isLocal: true,
  },
  {
    title: `suint3000xlcd`,
    brand: `Tripplite`,
    category: `Tripplite On-line`,
    href: `/manuals-pdfs/tripplite/tripplite-on-line/suint3000xlcd-d9831583.pdf`,
    sourceUrl: `https://onlitech.co.uk/wp-content/uploads/manuals/Tripplite/Tripplite On-Line/suint3000xlcd.pdf`,
    isLocal: true,
  },
];

export const manualBrands = [
  "All Brands",
  ...Array.from(new Set(manuals.map((manual) => manual.brand))).sort((a, b) =>
    a.localeCompare(b)
  ),
];
